repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        language_version: python2.7
        additional_dependencies:
        -   flake8==2.4.0
